id: PD2162A31
initial_creation_type: input
source_metadata:
  Title: Ḍākārṇavaḥ
  Editor: Nagendra Narayan Chaudhuri
  Publisher: Metropolitan Printing & Publishing House
  Place of Publication: Calcutta
  Year: '1935'
  डाकार्णवः:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:14:37.404113'
last_modified_at: '2022-03-08T17:14:37.404124'
